groups:
  - name: rental-management-alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(rental_management_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(rental_management_request_duration_seconds_bucket[5m])) > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # Service down
      - alert: ServiceDown
        expr: up{job="rental-management"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Rental Management Service is down"
          description: "The rental management service has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: rental_management_memory_usage_bytes{type="used"} / rental_management_memory_usage_bytes{type="total"} > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # High CPU usage
      - alert: HighCPUUsage
        expr: rental_management_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}%"

      # Low cache hit rate
      - alert: LowCacheHitRate
        expr: rate(rental_management_cache_hits_total[5m]) / (rate(rental_management_cache_hits_total[5m]) + rate(rental_management_cache_misses_total[5m])) < 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }}"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: rental_management_db_connections{status="active"} / rental_management_db_connections{status="total"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value | humanizePercentage }}"

      # Too many slow requests
      - alert: TooManySlowRequests
        expr: rate(rental_management_slow_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many slow requests"
          description: "Slow request rate is {{ $value }} requests per second"