"""Add comprehensive business modules - auth, customers, suppliers, locations

Revision ID: 6535bfe5de16
Revises: 5f8a6196db7c
Create Date: 2025-07-09 13:09:30.028010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6535bfe5de16'
down_revision = '5f8a6196db7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analytics_report_date_range', table_name='analytics_reports')
    op.drop_index('idx_analytics_report_generated_at', table_name='analytics_reports')
    op.drop_index('idx_analytics_report_generated_by', table_name='analytics_reports')
    op.drop_index('idx_analytics_report_status', table_name='analytics_reports')
    op.drop_index('idx_analytics_report_type', table_name='analytics_reports')
    op.drop_index('ix_analytics_reports_is_active', table_name='analytics_reports')
    op.drop_table('analytics_reports')
    op.drop_index('idx_rental_return_date', table_name='rental_returns')
    op.drop_index('idx_rental_return_expected_date', table_name='rental_returns')
    op.drop_index('idx_rental_return_location', table_name='rental_returns')
    op.drop_index('idx_rental_return_processed_by', table_name='rental_returns')
    op.drop_index('idx_rental_return_status', table_name='rental_returns')
    op.drop_index('idx_rental_return_transaction', table_name='rental_returns')
    op.drop_index('idx_rental_return_type', table_name='rental_returns')
    op.drop_index('ix_rental_returns_is_active', table_name='rental_returns')
    op.drop_table('rental_returns')
    op.drop_index('idx_inventory_unit_code', table_name='inventory_units')
    op.drop_index('idx_inventory_unit_condition', table_name='inventory_units')
    op.drop_index('idx_inventory_unit_item', table_name='inventory_units')
    op.drop_index('idx_inventory_unit_location', table_name='inventory_units')
    op.drop_index('idx_inventory_unit_serial', table_name='inventory_units')
    op.drop_index('idx_inventory_unit_status', table_name='inventory_units')
    op.drop_index('ix_inventory_units_is_active', table_name='inventory_units')
    op.drop_index('ix_inventory_units_unit_code', table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_index('idx_system_setting_active', table_name='system_settings')
    op.drop_index('idx_system_setting_category', table_name='system_settings')
    op.drop_index('idx_system_setting_display_order', table_name='system_settings')
    op.drop_index('idx_system_setting_key', table_name='system_settings')
    op.drop_index('idx_system_setting_system', table_name='system_settings')
    op.drop_index('idx_system_setting_type', table_name='system_settings')
    op.drop_index('ix_system_settings_is_active', table_name='system_settings')
    op.drop_index('ix_system_settings_setting_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('idx_system_backup_active', table_name='system_backups')
    op.drop_index('idx_system_backup_completed_at', table_name='system_backups')
    op.drop_index('idx_system_backup_name', table_name='system_backups')
    op.drop_index('idx_system_backup_started_at', table_name='system_backups')
    op.drop_index('idx_system_backup_started_by', table_name='system_backups')
    op.drop_index('idx_system_backup_status', table_name='system_backups')
    op.drop_index('idx_system_backup_type', table_name='system_backups')
    op.drop_index('ix_system_backups_is_active', table_name='system_backups')
    op.drop_table('system_backups')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.drop_index('idx_audit_log_active', table_name='audit_logs')
    op.drop_index('idx_audit_log_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_log_entity_id', table_name='audit_logs')
    op.drop_index('idx_audit_log_entity_type', table_name='audit_logs')
    op.drop_index('idx_audit_log_ip_address', table_name='audit_logs')
    op.drop_index('idx_audit_log_session_id', table_name='audit_logs')
    op.drop_index('idx_audit_log_success', table_name='audit_logs')
    op.drop_index('idx_audit_log_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_is_active', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_business_metric_category', table_name='business_metrics')
    op.drop_index('idx_business_metric_name', table_name='business_metrics')
    op.drop_index('idx_business_metric_name_date', table_name='business_metrics')
    op.drop_index('idx_business_metric_tracked_date', table_name='business_metrics')
    op.drop_index('idx_business_metric_type', table_name='business_metrics')
    op.drop_index('ix_business_metrics_is_active', table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index('idx_item_brand', table_name='items')
    op.drop_index('idx_item_category', table_name='items')
    op.drop_index('idx_item_code', table_name='items')
    op.drop_index('idx_item_name', table_name='items')
    op.drop_index('idx_item_status', table_name='items')
    op.drop_index('idx_item_supplier', table_name='items')
    op.drop_index('idx_item_type', table_name='items')
    op.drop_index('ix_items_item_code', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_transaction_lines_id', table_name='transaction_lines')
    op.drop_index('ix_transaction_lines_inventory_unit_id', table_name='transaction_lines')
    op.drop_index('ix_transaction_lines_is_active', table_name='transaction_lines')
    op.drop_index('ix_transaction_lines_item_id', table_name='transaction_lines')
    op.drop_index('ix_transaction_lines_line_type', table_name='transaction_lines')
    op.drop_index('ix_transaction_lines_transaction_id', table_name='transaction_lines')
    op.drop_table('transaction_lines')
    op.drop_index('idx_unit_abbreviation_active', table_name='units_of_measurement')
    op.drop_index('idx_unit_id_active', table_name='units_of_measurement')
    op.drop_index('idx_unit_name_active', table_name='units_of_measurement')
    op.drop_index('ix_units_of_measurement_abbreviation', table_name='units_of_measurement')
    op.drop_index('ix_units_of_measurement_id', table_name='units_of_measurement')
    op.drop_index('ix_units_of_measurement_is_active', table_name='units_of_measurement')
    op.drop_index('ix_units_of_measurement_name', table_name='units_of_measurement')
    op.drop_index('ix_units_of_measurement_unit_id', table_name='units_of_measurement')
    op.drop_table('units_of_measurement')
    op.drop_index('idx_transaction_customer', table_name='transaction_headers')
    op.drop_index('idx_transaction_date', table_name='transaction_headers')
    op.drop_index('idx_transaction_location', table_name='transaction_headers')
    op.drop_index('idx_transaction_number', table_name='transaction_headers')
    op.drop_index('idx_transaction_payment_status', table_name='transaction_headers')
    op.drop_index('idx_transaction_rental_dates', table_name='transaction_headers')
    op.drop_index('idx_transaction_sales_person', table_name='transaction_headers')
    op.drop_index('idx_transaction_status', table_name='transaction_headers')
    op.drop_index('idx_transaction_type', table_name='transaction_headers')
    op.drop_index('ix_transaction_headers_is_active', table_name='transaction_headers')
    op.drop_index('ix_transaction_headers_transaction_number', table_name='transaction_headers')
    op.drop_table('transaction_headers')
    op.drop_index('idx_address_customer', table_name='customer_addresses')
    op.drop_index('idx_address_customer_default', table_name='customer_addresses')
    op.drop_index('idx_address_location', table_name='customer_addresses')
    op.drop_index('idx_address_type_default', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_address_type', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_city', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_country', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_customer_id', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_id', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_is_active', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_is_default', table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_state', table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index('idx_stock_level_item', table_name='stock_levels')
    op.drop_index('idx_stock_level_item_location', table_name='stock_levels')
    op.drop_index('idx_stock_level_location', table_name='stock_levels')
    op.drop_index('ix_stock_levels_is_active', table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index('idx_inspection_report_damage_level', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_date', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_inspected_by', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_inventory_unit', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_return', table_name='inspection_reports')
    op.drop_index('idx_inspection_report_status', table_name='inspection_reports')
    op.drop_index('ix_inspection_reports_is_active', table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index('idx_system_alert_created_at', table_name='system_alerts')
    op.drop_index('idx_system_alert_name', table_name='system_alerts')
    op.drop_index('idx_system_alert_severity', table_name='system_alerts')
    op.drop_index('idx_system_alert_severity_status', table_name='system_alerts')
    op.drop_index('idx_system_alert_source', table_name='system_alerts')
    op.drop_index('idx_system_alert_status', table_name='system_alerts')
    op.drop_index('idx_system_alert_type', table_name='system_alerts')
    op.drop_table('system_alerts')
    op.drop_index('idx_rental_return_line_damage_level', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_inventory_unit', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_return', table_name='rental_return_lines')
    op.drop_index('idx_rental_return_line_status', table_name='rental_return_lines')
    op.drop_index('ix_rental_return_lines_is_active', table_name='rental_return_lines')
    op.drop_table('rental_return_lines')
    op.add_column('brands', sa.Column('name', sa.String(length=100), nullable=False, comment='Brand name'))
    op.add_column('brands', sa.Column('code', sa.String(length=20), nullable=True, comment='Unique brand code'))
    op.add_column('brands', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('brands', sa.Column('deleted_by', sa.String(length=255), nullable=True, comment='User who deleted the record'))
    op.alter_column('brands', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index('idx_brand_active', table_name='brands')
    op.drop_index('idx_brand_code', table_name='brands')
    op.drop_index('idx_brand_name', table_name='brands')
    op.drop_index('ix_brands_brand_code', table_name='brands')
    op.drop_index('ix_brands_brand_name', table_name='brands')
    op.drop_index('ix_brands_id', table_name='brands')
    op.drop_index('idx_brand_name_active', table_name='brands')
    op.create_index('idx_brand_name_active', 'brands', ['name', 'is_active'], unique=False)
    op.create_index('idx_brand_code_active', 'brands', ['code', 'is_active'], unique=False)
    op.create_index(op.f('ix_brands_code'), 'brands', ['code'], unique=True)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.drop_column('brands', 'brand_name')
    op.drop_column('brands', 'brand_code')
    op.add_column('categories', sa.Column('name', sa.String(length=100), nullable=False, comment='Category name'))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('categories', sa.Column('deleted_by', sa.String(length=255), nullable=True, comment='User who deleted the record'))
    op.alter_column('categories', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'updated_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_categories_category_name', table_name='categories')
    op.drop_index('ix_categories_parent_category_id', table_name='categories')
    op.create_index('idx_category_active_leaf', 'categories', ['is_active', 'is_leaf'], unique=False)
    op.create_index('idx_category_display_order', 'categories', ['display_order'], unique=False)
    op.create_index('idx_category_level', 'categories', ['category_level'], unique=False)
    op.create_index('idx_category_parent', 'categories', ['parent_category_id'], unique=False)
    op.create_index('idx_category_parent_order', 'categories', ['parent_category_id', 'display_order'], unique=False)
    op.create_index('idx_category_path', 'categories', ['category_path'], unique=False)
    op.create_index('uk_category_name_parent', 'categories', ['name', 'parent_category_id'], unique=True)
    op.drop_column('categories', 'category_name')
    op.add_column('locations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('locations', sa.Column('deleted_by', sa.String(length=255), nullable=True, comment='User who deleted the record'))
    op.alter_column('locations', 'location_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('locations', 'location_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('locations', 'location_type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_locations_city', table_name='locations')
    op.drop_index('ix_locations_country', table_name='locations')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_index('ix_locations_location_name', table_name='locations')
    op.drop_index('ix_locations_location_type', table_name='locations')
    op.drop_index('ix_locations_state', table_name='locations')
    op.create_index('idx_location_city', 'locations', ['city'], unique=False)
    op.create_index('idx_location_code', 'locations', ['location_code'], unique=False)
    op.create_index('idx_location_country', 'locations', ['country'], unique=False)
    op.create_index('idx_location_manager', 'locations', ['manager_user_id'], unique=False)
    op.create_index('idx_location_name', 'locations', ['location_name'], unique=False)
    op.create_index('idx_location_state', 'locations', ['state'], unique=False)
    op.create_index('idx_location_type', 'locations', ['location_type'], unique=False)
    op.add_column('suppliers', sa.Column('mobile', sa.String(length=50), nullable=True, comment='Supplier mobile number'))
    op.add_column('suppliers', sa.Column('address_line1', sa.String(length=255), nullable=True, comment='Primary address line'))
    op.add_column('suppliers', sa.Column('address_line2', sa.String(length=255), nullable=True, comment='Secondary address line'))
    op.add_column('suppliers', sa.Column('city', sa.String(length=100), nullable=True, comment='City'))
    op.add_column('suppliers', sa.Column('state', sa.String(length=100), nullable=True, comment='State/Province'))
    op.add_column('suppliers', sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal/ZIP code'))
    op.add_column('suppliers', sa.Column('country', sa.String(length=100), nullable=True, comment='Country'))
    op.add_column('suppliers', sa.Column('status', sa.String(length=20), nullable=False, comment='Supplier status'))
    op.add_column('suppliers', sa.Column('delivery_rating', sa.Numeric(precision=3, scale=2), nullable=False, comment='Delivery rating (0-5)'))
    op.add_column('suppliers', sa.Column('contract_start_date', sa.DateTime(), nullable=True, comment='Contract start date'))
    op.add_column('suppliers', sa.Column('contract_end_date', sa.DateTime(), nullable=True, comment='Contract end date'))
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'))
    op.add_column('suppliers', sa.Column('website', sa.String(length=255), nullable=True, comment='Supplier website'))
    op.add_column('suppliers', sa.Column('account_manager', sa.String(length=255), nullable=True, comment='Account manager name'))
    op.add_column('suppliers', sa.Column('preferred_payment_method', sa.String(length=50), nullable=True, comment='Preferred payment method'))
    op.add_column('suppliers', sa.Column('insurance_expiry', sa.DateTime(), nullable=True, comment='Insurance expiry date'))
    op.add_column('suppliers', sa.Column('certifications', sa.Text(), nullable=True, comment='Certifications held'))
    op.add_column('suppliers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'))
    op.add_column('suppliers', sa.Column('deleted_by', sa.String(length=255), nullable=True, comment='User who deleted the record'))
    op.alter_column('suppliers', 'supplier_type',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('suppliers', 'credit_limit',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'supplier_tier',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_suppliers_id', table_name='suppliers')
    op.drop_index('ix_suppliers_supplier_tier', table_name='suppliers')
    op.drop_index('ix_suppliers_supplier_type', table_name='suppliers')
    op.create_index('idx_supplier_code', 'suppliers', ['supplier_code'], unique=False)
    op.create_index('idx_supplier_company_name', 'suppliers', ['company_name'], unique=False)
    op.create_index('idx_supplier_contract_dates', 'suppliers', ['contract_start_date', 'contract_end_date'], unique=False)
    op.create_index('idx_supplier_email', 'suppliers', ['email'], unique=False)
    op.create_index('idx_supplier_last_order', 'suppliers', ['last_order_date'], unique=False)
    op.create_index('idx_supplier_payment_terms', 'suppliers', ['payment_terms'], unique=False)
    op.create_index('idx_supplier_ratings', 'suppliers', ['quality_rating', 'delivery_rating'], unique=False)
    op.create_index('idx_supplier_status', 'suppliers', ['status'], unique=False)
    op.create_index('idx_supplier_tier', 'suppliers', ['supplier_tier'], unique=False)
    op.create_index('idx_supplier_type', 'suppliers', ['supplier_type'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.drop_column('suppliers', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('address', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index('idx_supplier_type', table_name='suppliers')
    op.drop_index('idx_supplier_tier', table_name='suppliers')
    op.drop_index('idx_supplier_status', table_name='suppliers')
    op.drop_index('idx_supplier_ratings', table_name='suppliers')
    op.drop_index('idx_supplier_payment_terms', table_name='suppliers')
    op.drop_index('idx_supplier_last_order', table_name='suppliers')
    op.drop_index('idx_supplier_email', table_name='suppliers')
    op.drop_index('idx_supplier_contract_dates', table_name='suppliers')
    op.drop_index('idx_supplier_company_name', table_name='suppliers')
    op.drop_index('idx_supplier_code', table_name='suppliers')
    op.create_index('ix_suppliers_supplier_type', 'suppliers', ['supplier_type'], unique=False)
    op.create_index('ix_suppliers_supplier_tier', 'suppliers', ['supplier_tier'], unique=False)
    op.create_index('ix_suppliers_id', 'suppliers', ['id'], unique=False)
    op.alter_column('suppliers', 'supplier_tier',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('suppliers', 'credit_limit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('suppliers', 'supplier_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('suppliers', 'deleted_by')
    op.drop_column('suppliers', 'deleted_at')
    op.drop_column('suppliers', 'certifications')
    op.drop_column('suppliers', 'insurance_expiry')
    op.drop_column('suppliers', 'preferred_payment_method')
    op.drop_column('suppliers', 'account_manager')
    op.drop_column('suppliers', 'website')
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'contract_end_date')
    op.drop_column('suppliers', 'contract_start_date')
    op.drop_column('suppliers', 'delivery_rating')
    op.drop_column('suppliers', 'status')
    op.drop_column('suppliers', 'country')
    op.drop_column('suppliers', 'postal_code')
    op.drop_column('suppliers', 'state')
    op.drop_column('suppliers', 'city')
    op.drop_column('suppliers', 'address_line2')
    op.drop_column('suppliers', 'address_line1')
    op.drop_column('suppliers', 'mobile')
    op.drop_index('idx_location_type', table_name='locations')
    op.drop_index('idx_location_state', table_name='locations')
    op.drop_index('idx_location_name', table_name='locations')
    op.drop_index('idx_location_manager', table_name='locations')
    op.drop_index('idx_location_country', table_name='locations')
    op.drop_index('idx_location_code', table_name='locations')
    op.drop_index('idx_location_city', table_name='locations')
    op.create_index('ix_locations_state', 'locations', ['state'], unique=False)
    op.create_index('ix_locations_location_type', 'locations', ['location_type'], unique=False)
    op.create_index('ix_locations_location_name', 'locations', ['location_name'], unique=False)
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_index('ix_locations_country', 'locations', ['country'], unique=False)
    op.create_index('ix_locations_city', 'locations', ['city'], unique=False)
    op.alter_column('locations', 'location_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    op.alter_column('locations', 'location_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('locations', 'location_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('locations', 'deleted_by')
    op.drop_column('locations', 'deleted_at')
    op.add_column('categories', sa.Column('category_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index('uk_category_name_parent', table_name='categories')
    op.drop_index('idx_category_path', table_name='categories')
    op.drop_index('idx_category_parent_order', table_name='categories')
    op.drop_index('idx_category_parent', table_name='categories')
    op.drop_index('idx_category_level', table_name='categories')
    op.drop_index('idx_category_display_order', table_name='categories')
    op.drop_index('idx_category_active_leaf', table_name='categories')
    op.create_index('ix_categories_parent_category_id', 'categories', ['parent_category_id'], unique=False)
    op.create_index('ix_categories_category_name', 'categories', ['category_name'], unique=False)
    op.alter_column('categories', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('categories', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('categories', 'deleted_by')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'name')
    op.add_column('brands', sa.Column('brand_code', sa.VARCHAR(length=20), nullable=True))
    op.add_column('brands', sa.Column('brand_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_code'), table_name='brands')
    op.drop_index('idx_brand_code_active', table_name='brands')
    op.drop_index('idx_brand_name_active', table_name='brands')
    op.create_index('idx_brand_name_active', 'brands', ['brand_name', 'is_active'], unique=False)
    op.create_index('ix_brands_id', 'brands', ['id'], unique=False)
    op.create_index('ix_brands_brand_name', 'brands', ['brand_name'], unique=1)
    op.create_index('ix_brands_brand_code', 'brands', ['brand_code'], unique=1)
    op.create_index('idx_brand_name', 'brands', ['brand_name'], unique=False)
    op.create_index('idx_brand_code', 'brands', ['brand_code'], unique=False)
    op.create_index('idx_brand_active', 'brands', ['is_active'], unique=False)
    op.alter_column('brands', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('brands', 'deleted_by')
    op.drop_column('brands', 'deleted_at')
    op.drop_column('brands', 'code')
    op.drop_column('brands', 'name')
    op.create_table('rental_return_lines',
    sa.Column('rental_return_id', sa.CHAR(length=36), nullable=False),
    sa.Column('inventory_unit_id', sa.CHAR(length=36), nullable=False),
    sa.Column('original_quantity', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('returned_quantity', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('damage_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('line_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('late_fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('damage_fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['rental_return_id'], ['rental_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rental_return_lines_is_active', 'rental_return_lines', ['is_active'], unique=False)
    op.create_index('idx_rental_return_line_status', 'rental_return_lines', ['line_status'], unique=False)
    op.create_index('idx_rental_return_line_return', 'rental_return_lines', ['rental_return_id'], unique=False)
    op.create_index('idx_rental_return_line_inventory_unit', 'rental_return_lines', ['inventory_unit_id'], unique=False)
    op.create_index('idx_rental_return_line_damage_level', 'rental_return_lines', ['damage_level'], unique=False)
    op.create_table('system_alerts',
    sa.Column('alert_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('trigger_condition', sa.TEXT(), nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('acknowledged_by', sa.CHAR(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_by', sa.CHAR(length=36), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('alert_metadata', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_alert_type', 'system_alerts', ['alert_type'], unique=False)
    op.create_index('idx_system_alert_status', 'system_alerts', ['status'], unique=False)
    op.create_index('idx_system_alert_source', 'system_alerts', ['source'], unique=False)
    op.create_index('idx_system_alert_severity_status', 'system_alerts', ['severity', 'status'], unique=False)
    op.create_index('idx_system_alert_severity', 'system_alerts', ['severity'], unique=False)
    op.create_index('idx_system_alert_name', 'system_alerts', ['alert_name'], unique=False)
    op.create_index('idx_system_alert_created_at', 'system_alerts', ['created_at'], unique=False)
    op.create_table('inspection_reports',
    sa.Column('rental_return_id', sa.CHAR(length=36), nullable=False),
    sa.Column('inventory_unit_id', sa.CHAR(length=36), nullable=False),
    sa.Column('inspected_by', sa.CHAR(length=36), nullable=False),
    sa.Column('inspection_date', sa.DATETIME(), nullable=False),
    sa.Column('inspection_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('damage_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('damage_description', sa.TEXT(), nullable=True),
    sa.Column('repair_cost_estimate', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('replacement_cost_estimate', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('inspection_notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['rental_return_id'], ['rental_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_reports_is_active', 'inspection_reports', ['is_active'], unique=False)
    op.create_index('idx_inspection_report_status', 'inspection_reports', ['inspection_status'], unique=False)
    op.create_index('idx_inspection_report_return', 'inspection_reports', ['rental_return_id'], unique=False)
    op.create_index('idx_inspection_report_inventory_unit', 'inspection_reports', ['inventory_unit_id'], unique=False)
    op.create_index('idx_inspection_report_inspected_by', 'inspection_reports', ['inspected_by'], unique=False)
    op.create_index('idx_inspection_report_date', 'inspection_reports', ['inspection_date'], unique=False)
    op.create_index('idx_inspection_report_damage_level', 'inspection_reports', ['damage_level'], unique=False)
    op.create_table('stock_levels',
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.Column('quantity_on_hand', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity_available', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity_reserved', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity_on_order', sa.VARCHAR(length=10), nullable=False),
    sa.Column('minimum_level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('maximum_level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('reorder_point', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_levels_is_active', 'stock_levels', ['is_active'], unique=False)
    op.create_index('idx_stock_level_location', 'stock_levels', ['location_id'], unique=False)
    op.create_index('idx_stock_level_item_location', 'stock_levels', ['item_id', 'location_id'], unique=1)
    op.create_index('idx_stock_level_item', 'stock_levels', ['item_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('customer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('address_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('street', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address_line2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_addresses_state', 'customer_addresses', ['state'], unique=False)
    op.create_index('ix_customer_addresses_is_default', 'customer_addresses', ['is_default'], unique=False)
    op.create_index('ix_customer_addresses_is_active', 'customer_addresses', ['is_active'], unique=False)
    op.create_index('ix_customer_addresses_id', 'customer_addresses', ['id'], unique=False)
    op.create_index('ix_customer_addresses_customer_id', 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('ix_customer_addresses_country', 'customer_addresses', ['country'], unique=False)
    op.create_index('ix_customer_addresses_city', 'customer_addresses', ['city'], unique=False)
    op.create_index('ix_customer_addresses_address_type', 'customer_addresses', ['address_type'], unique=False)
    op.create_index('idx_address_type_default', 'customer_addresses', ['customer_id', 'address_type', 'is_default'], unique=False)
    op.create_index('idx_address_location', 'customer_addresses', ['city', 'state', 'country'], unique=False)
    op.create_index('idx_address_customer_default', 'customer_addresses', ['customer_id', 'is_default'], unique=False)
    op.create_index('idx_address_customer', 'customer_addresses', ['customer_id', 'is_active'], unique=False)
    op.create_table('transaction_headers',
    sa.Column('transaction_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('transaction_date', sa.DATETIME(), nullable=False),
    sa.Column('customer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sales_person_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('reference_transaction_id', sa.CHAR(length=36), nullable=True),
    sa.Column('rental_start_date', sa.DATE(), nullable=True),
    sa.Column('rental_end_date', sa.DATE(), nullable=True),
    sa.Column('actual_return_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reference_transaction_id'], ['transaction_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_headers_transaction_number', 'transaction_headers', ['transaction_number'], unique=1)
    op.create_index('ix_transaction_headers_is_active', 'transaction_headers', ['is_active'], unique=False)
    op.create_index('idx_transaction_type', 'transaction_headers', ['transaction_type'], unique=False)
    op.create_index('idx_transaction_status', 'transaction_headers', ['status'], unique=False)
    op.create_index('idx_transaction_sales_person', 'transaction_headers', ['sales_person_id'], unique=False)
    op.create_index('idx_transaction_rental_dates', 'transaction_headers', ['rental_start_date', 'rental_end_date'], unique=False)
    op.create_index('idx_transaction_payment_status', 'transaction_headers', ['payment_status'], unique=False)
    op.create_index('idx_transaction_number', 'transaction_headers', ['transaction_number'], unique=False)
    op.create_index('idx_transaction_location', 'transaction_headers', ['location_id'], unique=False)
    op.create_index('idx_transaction_date', 'transaction_headers', ['transaction_date'], unique=False)
    op.create_index('idx_transaction_customer', 'transaction_headers', ['customer_id'], unique=False)
    op.create_table('units_of_measurement',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('unit_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=10), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_units_of_measurement_unit_id', 'units_of_measurement', ['unit_id'], unique=1)
    op.create_index('ix_units_of_measurement_name', 'units_of_measurement', ['name'], unique=False)
    op.create_index('ix_units_of_measurement_is_active', 'units_of_measurement', ['is_active'], unique=False)
    op.create_index('ix_units_of_measurement_id', 'units_of_measurement', ['id'], unique=False)
    op.create_index('ix_units_of_measurement_abbreviation', 'units_of_measurement', ['abbreviation'], unique=False)
    op.create_index('idx_unit_name_active', 'units_of_measurement', ['name', 'is_active'], unique=False)
    op.create_index('idx_unit_id_active', 'units_of_measurement', ['unit_id', 'is_active'], unique=False)
    op.create_index('idx_unit_abbreviation_active', 'units_of_measurement', ['abbreviation', 'is_active'], unique=False)
    op.create_table('transaction_lines',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('transaction_id', sa.CHAR(length=36), nullable=False),
    sa.Column('line_number', sa.INTEGER(), nullable=False),
    sa.Column('line_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('item_id', sa.CHAR(length=36), nullable=True),
    sa.Column('inventory_unit_id', sa.CHAR(length=36), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=3), server_default=sa.text("'1'"), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('line_total', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('rental_period_value', sa.INTEGER(), nullable=True),
    sa.Column('rental_period_unit', sa.VARCHAR(length=5), nullable=True),
    sa.Column('rental_start_date', sa.DATE(), nullable=True),
    sa.Column('rental_end_date', sa.DATE(), nullable=True),
    sa.Column('returned_quantity', sa.NUMERIC(precision=10, scale=3), server_default=sa.text("'0'"), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_unit_id'], ['inventory_units.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_lines_transaction_id', 'transaction_lines', ['transaction_id'], unique=False)
    op.create_index('ix_transaction_lines_line_type', 'transaction_lines', ['line_type'], unique=False)
    op.create_index('ix_transaction_lines_item_id', 'transaction_lines', ['item_id'], unique=False)
    op.create_index('ix_transaction_lines_is_active', 'transaction_lines', ['is_active'], unique=False)
    op.create_index('ix_transaction_lines_inventory_unit_id', 'transaction_lines', ['inventory_unit_id'], unique=False)
    op.create_index('ix_transaction_lines_id', 'transaction_lines', ['id'], unique=False)
    op.create_table('items',
    sa.Column('item_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('item_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('brand_id', sa.CHAR(length=36), nullable=True),
    sa.Column('category_id', sa.CHAR(length=36), nullable=True),
    sa.Column('unit_of_measurement_id', sa.CHAR(length=36), nullable=True),
    sa.Column('supplier_id', sa.CHAR(length=36), nullable=True),
    sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('rental_price_per_day', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rental_price_per_week', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rental_price_per_month', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('minimum_rental_days', sa.VARCHAR(length=10), nullable=True),
    sa.Column('maximum_rental_days', sa.VARCHAR(length=10), nullable=True),
    sa.Column('security_deposit', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('specifications', sa.TEXT(), nullable=True),
    sa.Column('model_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serial_number_required', sa.BOOLEAN(), nullable=False),
    sa.Column('warranty_period_days', sa.VARCHAR(length=10), nullable=False),
    sa.Column('reorder_level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('reorder_quantity', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_item_code', 'items', ['item_code'], unique=1)
    op.create_index('idx_item_type', 'items', ['item_type'], unique=False)
    op.create_index('idx_item_supplier', 'items', ['supplier_id'], unique=False)
    op.create_index('idx_item_status', 'items', ['item_status'], unique=False)
    op.create_index('idx_item_name', 'items', ['item_name'], unique=False)
    op.create_index('idx_item_code', 'items', ['item_code'], unique=False)
    op.create_index('idx_item_category', 'items', ['category_id'], unique=False)
    op.create_index('idx_item_brand', 'items', ['brand_id'], unique=False)
    op.create_table('business_metrics',
    sa.Column('metric_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('current_value', sa.NUMERIC(precision=15, scale=4), nullable=False),
    sa.Column('previous_value', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('target_value', sa.NUMERIC(precision=15, scale=4), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('calculation_method', sa.TEXT(), nullable=True),
    sa.Column('tracked_date', sa.DATETIME(), nullable=False),
    sa.Column('metric_metadata', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_metrics_is_active', 'business_metrics', ['is_active'], unique=False)
    op.create_index('idx_business_metric_type', 'business_metrics', ['metric_type'], unique=False)
    op.create_index('idx_business_metric_tracked_date', 'business_metrics', ['tracked_date'], unique=False)
    op.create_index('idx_business_metric_name_date', 'business_metrics', ['metric_name', 'tracked_date'], unique=False)
    op.create_index('idx_business_metric_name', 'business_metrics', ['metric_name'], unique=False)
    op.create_index('idx_business_metric_category', 'business_metrics', ['category'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('entity_id', sa.CHAR(length=36), nullable=True),
    sa.Column('old_values', sqlite.JSON(), nullable=True),
    sa.Column('new_values', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('audit_metadata', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_is_active', 'audit_logs', ['is_active'], unique=False)
    op.create_index('idx_audit_log_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_log_success', 'audit_logs', ['success'], unique=False)
    op.create_index('idx_audit_log_session_id', 'audit_logs', ['session_id'], unique=False)
    op.create_index('idx_audit_log_ip_address', 'audit_logs', ['ip_address'], unique=False)
    op.create_index('idx_audit_log_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('idx_audit_log_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_log_active', 'audit_logs', ['is_active'], unique=False)
    op.create_index('idx_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_table('system_backups',
    sa.Column('backup_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('backup_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('backup_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('backup_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('backup_size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('started_by', sa.CHAR(length=36), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retention_days', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('backup_metadata', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_backups_is_active', 'system_backups', ['is_active'], unique=False)
    op.create_index('idx_system_backup_type', 'system_backups', ['backup_type'], unique=False)
    op.create_index('idx_system_backup_status', 'system_backups', ['backup_status'], unique=False)
    op.create_index('idx_system_backup_started_by', 'system_backups', ['started_by'], unique=False)
    op.create_index('idx_system_backup_started_at', 'system_backups', ['started_at'], unique=False)
    op.create_index('idx_system_backup_name', 'system_backups', ['backup_name'], unique=False)
    op.create_index('idx_system_backup_completed_at', 'system_backups', ['completed_at'], unique=False)
    op.create_index('idx_system_backup_active', 'system_backups', ['is_active'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('setting_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('setting_category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('setting_value', sa.TEXT(), nullable=True),
    sa.Column('default_value', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), nullable=False),
    sa.Column('validation_rules', sqlite.JSON(), nullable=True),
    sa.Column('display_order', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_settings_setting_key', 'system_settings', ['setting_key'], unique=1)
    op.create_index('ix_system_settings_is_active', 'system_settings', ['is_active'], unique=False)
    op.create_index('idx_system_setting_type', 'system_settings', ['setting_type'], unique=False)
    op.create_index('idx_system_setting_system', 'system_settings', ['is_system'], unique=False)
    op.create_index('idx_system_setting_key', 'system_settings', ['setting_key'], unique=False)
    op.create_index('idx_system_setting_display_order', 'system_settings', ['display_order'], unique=False)
    op.create_index('idx_system_setting_category', 'system_settings', ['setting_category'], unique=False)
    op.create_index('idx_system_setting_active', 'system_settings', ['is_active'], unique=False)
    op.create_table('inventory_units',
    sa.Column('item_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.Column('unit_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=20), nullable=False),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.Column('purchase_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('warranty_expiry', sa.DATETIME(), nullable=True),
    sa.Column('last_maintenance_date', sa.DATETIME(), nullable=True),
    sa.Column('next_maintenance_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_units_unit_code', 'inventory_units', ['unit_code'], unique=1)
    op.create_index('ix_inventory_units_is_active', 'inventory_units', ['is_active'], unique=False)
    op.create_index('idx_inventory_unit_status', 'inventory_units', ['status'], unique=False)
    op.create_index('idx_inventory_unit_serial', 'inventory_units', ['serial_number'], unique=False)
    op.create_index('idx_inventory_unit_location', 'inventory_units', ['location_id'], unique=False)
    op.create_index('idx_inventory_unit_item', 'inventory_units', ['item_id'], unique=False)
    op.create_index('idx_inventory_unit_condition', 'inventory_units', ['condition'], unique=False)
    op.create_index('idx_inventory_unit_code', 'inventory_units', ['unit_code'], unique=False)
    op.create_table('rental_returns',
    sa.Column('rental_transaction_id', sa.CHAR(length=36), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=False),
    sa.Column('return_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('return_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('return_location_id', sa.CHAR(length=36), nullable=True),
    sa.Column('expected_return_date', sa.DATE(), nullable=True),
    sa.Column('processed_by', sa.CHAR(length=36), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('total_late_fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_damage_fee', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_deposit_release', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_refund_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rental_transaction_id'], ['transaction_headers.id'], ),
    sa.ForeignKeyConstraint(['return_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rental_returns_is_active', 'rental_returns', ['is_active'], unique=False)
    op.create_index('idx_rental_return_type', 'rental_returns', ['return_type'], unique=False)
    op.create_index('idx_rental_return_transaction', 'rental_returns', ['rental_transaction_id'], unique=False)
    op.create_index('idx_rental_return_status', 'rental_returns', ['return_status'], unique=False)
    op.create_index('idx_rental_return_processed_by', 'rental_returns', ['processed_by'], unique=False)
    op.create_index('idx_rental_return_location', 'rental_returns', ['return_location_id'], unique=False)
    op.create_index('idx_rental_return_expected_date', 'rental_returns', ['expected_return_date'], unique=False)
    op.create_index('idx_rental_return_date', 'rental_returns', ['return_date'], unique=False)
    op.create_table('analytics_reports',
    sa.Column('report_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('report_format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('report_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('filters', sqlite.JSON(), nullable=True),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('generated_by', sa.CHAR(length=36), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('report_metadata', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_reports_is_active', 'analytics_reports', ['is_active'], unique=False)
    op.create_index('idx_analytics_report_type', 'analytics_reports', ['report_type'], unique=False)
    op.create_index('idx_analytics_report_status', 'analytics_reports', ['report_status'], unique=False)
    op.create_index('idx_analytics_report_generated_by', 'analytics_reports', ['generated_by'], unique=False)
    op.create_index('idx_analytics_report_generated_at', 'analytics_reports', ['generated_at'], unique=False)
    op.create_index('idx_analytics_report_date_range', 'analytics_reports', ['start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###