"""Complete rental management system migration

Revision ID: complete_rental_system
Revises: f1ee268d99bb
Create Date: 2025-01-09 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'complete_rental_system'
down_revision: Union[str, None] = 'f1ee268d99bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables for the complete rental management system."""
    
    # Create master data tables
    op.create_table('brands',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('code', sa.String(20), nullable=False, unique=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('logo_url', sa.String(255), nullable=True),
        sa.Column('website_url', sa.String(255), nullable=True),
        sa.Column('contact_email', sa.String(100), nullable=True),
        sa.Column('contact_phone', sa.String(20), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, default='ACTIVE'),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_brands_name', 'name'),
        sa.Index('idx_brands_code', 'code'),
        sa.Index('idx_brands_status', 'status'),
        sa.Index('idx_brands_active', 'is_active'),
    )
    
    op.create_table('categories',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('code', sa.String(20), nullable=False, unique=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('parent_id', sa.String(36), sa.ForeignKey('categories.id'), nullable=True),
        sa.Column('category_type', sa.String(20), nullable=False),
        sa.Column('icon_url', sa.String(255), nullable=True),
        sa.Column('color_code', sa.String(7), nullable=True),
        sa.Column('sort_order', sa.Integer, nullable=False, default=0),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_categories_name', 'name'),
        sa.Index('idx_categories_code', 'code'),
        sa.Index('idx_categories_parent_id', 'parent_id'),
        sa.Index('idx_categories_type', 'category_type'),
        sa.Index('idx_categories_active', 'is_active'),
    )
    
    op.create_table('locations',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('code', sa.String(20), nullable=False, unique=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('location_type', sa.String(20), nullable=False),
        sa.Column('address_line1', sa.String(200), nullable=True),
        sa.Column('address_line2', sa.String(200), nullable=True),
        sa.Column('city', sa.String(100), nullable=True),
        sa.Column('state', sa.String(100), nullable=True),
        sa.Column('postal_code', sa.String(20), nullable=True),
        sa.Column('country', sa.String(100), nullable=True),
        sa.Column('coordinates', sa.JSON, nullable=True),
        sa.Column('capacity', sa.Integer, nullable=True),
        sa.Column('manager_name', sa.String(100), nullable=True),
        sa.Column('manager_email', sa.String(100), nullable=True),
        sa.Column('manager_phone', sa.String(20), nullable=True),
        sa.Column('operating_hours', sa.JSON, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_locations_name', 'name'),
        sa.Index('idx_locations_code', 'code'),
        sa.Index('idx_locations_type', 'location_type'),
        sa.Index('idx_locations_city', 'city'),
        sa.Index('idx_locations_active', 'is_active'),
    )
    
    # Create roles and permissions tables
    op.create_table('roles',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('is_system', sa.Boolean, nullable=False, default=False),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_roles_name', 'name'),
        sa.Index('idx_roles_system', 'is_system'),
        sa.Index('idx_roles_active', 'is_active'),
    )
    
    op.create_table('permissions',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('resource', sa.String(100), nullable=False),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('is_system', sa.Boolean, nullable=False, default=False),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_permissions_name', 'name'),
        sa.Index('idx_permissions_resource', 'resource'),
        sa.Index('idx_permissions_action', 'action'),
        sa.Index('idx_permissions_system', 'is_system'),
        sa.Index('idx_permissions_active', 'is_active'),
    )
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('username', sa.String(100), nullable=False, unique=True),
        sa.Column('email', sa.String(100), nullable=False, unique=True),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('avatar_url', sa.String(255), nullable=True),
        sa.Column('last_login', sa.DateTime, nullable=True),
        sa.Column('login_count', sa.Integer, nullable=False, default=0),
        sa.Column('failed_login_attempts', sa.Integer, nullable=False, default=0),
        sa.Column('is_locked', sa.Boolean, nullable=False, default=False),
        sa.Column('locked_at', sa.DateTime, nullable=True),
        sa.Column('password_changed_at', sa.DateTime, nullable=True),
        sa.Column('email_verified', sa.Boolean, nullable=False, default=False),
        sa.Column('email_verified_at', sa.DateTime, nullable=True),
        sa.Column('preferences', sa.JSON, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_users_username', 'username'),
        sa.Index('idx_users_email', 'email'),
        sa.Index('idx_users_last_login', 'last_login'),
        sa.Index('idx_users_active', 'is_active'),
    )
    
    # Create junction tables
    op.create_table('user_roles',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('role_id', sa.String(36), sa.ForeignKey('roles.id'), nullable=False),
        sa.Column('granted_by', sa.String(36), nullable=True),
        sa.Column('granted_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('expires_at', sa.DateTime, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_user_roles_user_id', 'user_id'),
        sa.Index('idx_user_roles_role_id', 'role_id'),
        sa.Index('idx_user_roles_active', 'is_active'),
        sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles'),
    )
    
    op.create_table('role_permissions',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('role_id', sa.String(36), sa.ForeignKey('roles.id'), nullable=False),
        sa.Column('permission_id', sa.String(36), sa.ForeignKey('permissions.id'), nullable=False),
        sa.Column('granted_by', sa.String(36), nullable=True),
        sa.Column('granted_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_role_permissions_role_id', 'role_id'),
        sa.Index('idx_role_permissions_permission_id', 'permission_id'),
        sa.Index('idx_role_permissions_active', 'is_active'),
        sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions'),
    )
    
    # Create suppliers table
    op.create_table('suppliers',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('code', sa.String(50), nullable=False, unique=True),
        sa.Column('supplier_type', sa.String(20), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, default='ACTIVE'),
        sa.Column('tax_id', sa.String(50), nullable=True),
        sa.Column('registration_number', sa.String(50), nullable=True),
        sa.Column('contact_person', sa.String(100), nullable=True),
        sa.Column('email', sa.String(100), nullable=True),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('website', sa.String(255), nullable=True),
        sa.Column('address_line1', sa.String(200), nullable=True),
        sa.Column('address_line2', sa.String(200), nullable=True),
        sa.Column('city', sa.String(100), nullable=True),
        sa.Column('state', sa.String(100), nullable=True),
        sa.Column('postal_code', sa.String(20), nullable=True),
        sa.Column('country', sa.String(100), nullable=True),
        sa.Column('payment_terms', sa.String(100), nullable=True),
        sa.Column('credit_limit', sa.Numeric(15, 2), nullable=True),
        sa.Column('discount_rate', sa.Numeric(5, 4), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_suppliers_name', 'name'),
        sa.Index('idx_suppliers_code', 'code'),
        sa.Index('idx_suppliers_type', 'supplier_type'),
        sa.Index('idx_suppliers_status', 'status'),
        sa.Index('idx_suppliers_active', 'is_active'),
    )
    
    # Create customers table
    op.create_table('customers',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('customer_number', sa.String(50), nullable=False, unique=True),
        sa.Column('customer_type', sa.String(20), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, default='ACTIVE'),
        sa.Column('first_name', sa.String(100), nullable=True),
        sa.Column('last_name', sa.String(100), nullable=True),
        sa.Column('company_name', sa.String(200), nullable=True),
        sa.Column('email', sa.String(100), nullable=True),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('mobile', sa.String(20), nullable=True),
        sa.Column('date_of_birth', sa.Date, nullable=True),
        sa.Column('tax_id', sa.String(50), nullable=True),
        sa.Column('credit_limit', sa.Numeric(15, 2), nullable=True),
        sa.Column('payment_terms', sa.String(100), nullable=True),
        sa.Column('preferred_contact_method', sa.String(20), nullable=True),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_customers_number', 'customer_number'),
        sa.Index('idx_customers_type', 'customer_type'),
        sa.Index('idx_customers_status', 'status'),
        sa.Index('idx_customers_email', 'email'),
        sa.Index('idx_customers_phone', 'phone'),
        sa.Index('idx_customers_active', 'is_active'),
    )
    
    # Create customer related tables
    op.create_table('customer_contacts',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('customer_id', sa.String(36), sa.ForeignKey('customers.id'), nullable=False),
        sa.Column('contact_type', sa.String(20), nullable=False),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('title', sa.String(100), nullable=True),
        sa.Column('department', sa.String(100), nullable=True),
        sa.Column('email', sa.String(100), nullable=True),
        sa.Column('phone', sa.String(20), nullable=True),
        sa.Column('mobile', sa.String(20), nullable=True),
        sa.Column('is_primary', sa.Boolean, nullable=False, default=False),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_customer_contacts_customer_id', 'customer_id'),
        sa.Index('idx_customer_contacts_type', 'contact_type'),
        sa.Index('idx_customer_contacts_primary', 'is_primary'),
        sa.Index('idx_customer_contacts_active', 'is_active'),
    )
    
    op.create_table('customer_addresses',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('customer_id', sa.String(36), sa.ForeignKey('customers.id'), nullable=False),
        sa.Column('address_type', sa.String(20), nullable=False),
        sa.Column('address_line1', sa.String(200), nullable=False),
        sa.Column('address_line2', sa.String(200), nullable=True),
        sa.Column('city', sa.String(100), nullable=False),
        sa.Column('state', sa.String(100), nullable=False),
        sa.Column('postal_code', sa.String(20), nullable=False),
        sa.Column('country', sa.String(100), nullable=False),
        sa.Column('is_primary', sa.Boolean, nullable=False, default=False),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_customer_addresses_customer_id', 'customer_id'),
        sa.Index('idx_customer_addresses_type', 'address_type'),
        sa.Index('idx_customer_addresses_primary', 'is_primary'),
        sa.Index('idx_customer_addresses_city', 'city'),
        sa.Index('idx_customer_addresses_active', 'is_active'),
    )
    
    # Create inventory tables
    op.create_table('inventory_items',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('code', sa.String(50), nullable=False, unique=True),
        sa.Column('barcode', sa.String(100), nullable=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('brand_id', sa.String(36), sa.ForeignKey('brands.id'), nullable=True),
        sa.Column('category_id', sa.String(36), sa.ForeignKey('categories.id'), nullable=True),
        sa.Column('supplier_id', sa.String(36), sa.ForeignKey('suppliers.id'), nullable=True),
        sa.Column('item_type', sa.String(20), nullable=False),
        sa.Column('item_condition', sa.String(20), nullable=False),
        sa.Column('purchase_price', sa.Numeric(15, 2), nullable=True),
        sa.Column('rental_price', sa.Numeric(15, 2), nullable=True),
        sa.Column('daily_rate', sa.Numeric(15, 2), nullable=True),
        sa.Column('weekly_rate', sa.Numeric(15, 2), nullable=True),
        sa.Column('monthly_rate', sa.Numeric(15, 2), nullable=True),
        sa.Column('replacement_cost', sa.Numeric(15, 2), nullable=True),
        sa.Column('serial_number', sa.String(100), nullable=True),
        sa.Column('model_number', sa.String(100), nullable=True),
        sa.Column('year_manufactured', sa.Integer, nullable=True),
        sa.Column('weight', sa.Numeric(10, 2), nullable=True),
        sa.Column('dimensions', sa.JSON, nullable=True),
        sa.Column('color', sa.String(50), nullable=True),
        sa.Column('material', sa.String(100), nullable=True),
        sa.Column('warranty_info', sa.Text, nullable=True),
        sa.Column('maintenance_schedule', sa.JSON, nullable=True),
        sa.Column('images', sa.JSON, nullable=True),
        sa.Column('specifications', sa.JSON, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_inventory_items_name', 'name'),
        sa.Index('idx_inventory_items_code', 'code'),
        sa.Index('idx_inventory_items_barcode', 'barcode'),
        sa.Index('idx_inventory_items_brand_id', 'brand_id'),
        sa.Index('idx_inventory_items_category_id', 'category_id'),
        sa.Index('idx_inventory_items_supplier_id', 'supplier_id'),
        sa.Index('idx_inventory_items_type', 'item_type'),
        sa.Index('idx_inventory_items_condition', 'item_condition'),
        sa.Index('idx_inventory_items_serial', 'serial_number'),
        sa.Index('idx_inventory_items_active', 'is_active'),
    )
    
    # Create system management tables
    op.create_table('system_settings',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('setting_key', sa.String(100), nullable=False, unique=True),
        sa.Column('setting_name', sa.String(200), nullable=False),
        sa.Column('setting_type', sa.String(20), nullable=False),
        sa.Column('setting_category', sa.String(20), nullable=False),
        sa.Column('setting_value', sa.Text, nullable=True),
        sa.Column('default_value', sa.Text, nullable=True),
        sa.Column('description', sa.Text, nullable=True),
        sa.Column('is_system', sa.Boolean, nullable=False, default=False),
        sa.Column('is_sensitive', sa.Boolean, nullable=False, default=False),
        sa.Column('validation_rules', sa.JSON, nullable=True),
        sa.Column('display_order', sa.String(10), nullable=False, default='0'),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_system_setting_key', 'setting_key'),
        sa.Index('idx_system_setting_category', 'setting_category'),
        sa.Index('idx_system_setting_type', 'setting_type'),
        sa.Index('idx_system_setting_system', 'is_system'),
        sa.Index('idx_system_setting_display_order', 'display_order'),
        sa.Index('idx_system_setting_active', 'is_active'),
    )
    
    # Create audit logs table
    op.create_table('audit_logs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('action', sa.String(50), nullable=False),
        sa.Column('entity_type', sa.String(100), nullable=True),
        sa.Column('entity_id', sa.String(36), nullable=True),
        sa.Column('old_values', sa.JSON, nullable=True),
        sa.Column('new_values', sa.JSON, nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.Text, nullable=True),
        sa.Column('session_id', sa.String(100), nullable=True),
        sa.Column('success', sa.Boolean, nullable=False, default=True),
        sa.Column('error_message', sa.Text, nullable=True),
        sa.Column('metadata', sa.JSON, nullable=True),
        sa.Column('is_active', sa.Boolean, nullable=False, default=True),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by', sa.String(255), nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('version', sa.Integer, nullable=False, default=1),
        sa.Index('idx_audit_log_user_id', 'user_id'),
        sa.Index('idx_audit_log_action', 'action'),
        sa.Index('idx_audit_log_entity_type', 'entity_type'),
        sa.Index('idx_audit_log_entity_id', 'entity_id'),
        sa.Index('idx_audit_log_created_at', 'created_at'),
        sa.Index('idx_audit_log_success', 'success'),
        sa.Index('idx_audit_log_ip_address', 'ip_address'),
        sa.Index('idx_audit_log_session_id', 'session_id'),
        sa.Index('idx_audit_log_active', 'is_active'),
    )


def downgrade() -> None:
    """Drop all tables."""
    op.drop_table('audit_logs')
    op.drop_table('system_settings')
    op.drop_table('inventory_items')
    op.drop_table('customer_addresses')
    op.drop_table('customer_contacts')
    op.drop_table('customers')
    op.drop_table('suppliers')
    op.drop_table('role_permissions')
    op.drop_table('user_roles')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_table('categories')
    op.drop_table('brands')