apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-api-config
  namespace: rental-management
data:
  APP_NAME: "Rental Management System"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "4"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: '["https://your-domain.com"]'
  RATE_LIMIT_ENABLED: "true"
  FEATURE_ANALYTICS_ENABLED: "true"
  FEATURE_WEBHOOKS_ENABLED: "true"
  API_DOCS_ENABLED: "true"
  TIMEZONE: "UTC"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: rental-management
data:
  POSTGRES_DB: "rental_management"
  POSTGRES_USER: "rental_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: rental-management
data:
  redis.conf: |
    # Redis configuration for production
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    timeout 300
    tcp-keepalive 300