apiVersion: v1
kind: Secret
metadata:
  name: rental-api-secret
  namespace: rental-management
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcmVudGFsX3VzZXI6cmVudGFsX3Bhc3N3b3JkQHBvc3RncmVzOjU0MzIvcmVudGFsX21hbmFnZW1lbnQ=
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNzM5LzA=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rental-management
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: cmVudGFsX3Bhc3N3b3Jk  # rental_password
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: rental-management
type: Opaque
data:
  # Base64 encoded Stripe keys
  STRIPE_SECRET_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5
  STRIPE_WEBHOOK_SECRET: d2hzZWNfeW91cl93ZWJob29rX3NlY3JldA==