global:
  scrape_interval: 60s
  evaluation_interval: 60s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Rental Management System API
  - job_name: 'rental-management'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/prometheus'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Application health check
  - job_name: 'rental-health'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/health'
    scrape_interval: 2m